#!/usr/bin/env python2
import sys


def get_firsts_for_file_handle(fh):
    database_set = set()
    rstrip = str.rstrip
    dadd = database_set.add
    for l in fh:
        l = rstrip(l)
        data = hash(l)
        if data not in database_set:
            yield l
            dadd(data)


def get_version():
    return "1.1.0"


if __name__ == "__main__":
    from argparse import ArgumentParser

    parser = ArgumentParser(
        prog=__file__,
        description="Prints out the first unique instance of a line",
        version="%(prog)s v" + get_version() + " by Brian Wallace (@botnet_hunter)",
        epilog="%(prog)s v" + get_version() + " by Brian Wallace (@botnet_hunter)"
    )
    parser.add_argument('path', metavar='path', type=str, nargs='?', default="-",
                        help="Paths to files to scan (if not supplied, stdin is the file being read)")

    args = parser.parse_args()

    try:
        with sys.stdin if args.path == "-" else open(args.path, 'r') as fh:
            for line in get_firsts_for_file_handle(fh):
                print line
    except KeyboardInterrupt:
        pass
    except Exception as ex:
        print ex
    finally:
        try:
            sys.stdout.close()
        except:
            pass
        try:
            sys.stderr.close()
        except:
            pass
